# Generated by Django 4.2.11 on 2024-10-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManager', '0002_alter_category_category_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_for_user',
        ),
    ]
