# Generated by Django 4.2.11 on 2024-10-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManager', '0003_remove_category_unique_category_for_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'category_type'), name='unique_category_for_user'),
        ),
    ]
