# Generated by Django 4.2.11 on 2024-10-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManager', '0004_category_unique_category_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7),
        ),
    ]
