# Generated by Django 4.2.11 on 2024-10-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManager', '0005_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=7),
        ),
    ]
