# Generated by Django 4.2.11 on 2024-10-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManager', '0007_rename_category_type_category_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='transaction_type',
            new_name='category_type',
        ),
    ]
