# Generated by Django 4.2.15 on 2024-10-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceManager', '0008_rename_transaction_type_category_category_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
